# Generated by Django 3.2.4 on 2021-06-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='state',
            new_name='is_done',
        ),
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
